# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('rating', models.FloatField(blank=True, default=0, null=True)),
                ('description', models.TextField(max_length=200)),
                ('genre', models.CharField(max_length=10)),
                ('images', models.ImageField(height_field='1920', upload_to='siteimages/', width_field='1080')),
            ],
        ),
    ]
